// Word export utility for trading contract analysis results
// Note: This is a simplified version. For production, use a library like docxtemplater or docx

export interface WordExportData {
  title: string;
  summary: string;
  redFlags: Array<{ title: string; description: string; severity: string }>;
  suggestions: Array<{ section: string; suggested: string; explanation: string }>;
  riskScore: number;
}

export const exportToWord = (data: WordExportData): void => {
  // Create a simple HTML document that can be opened in Word
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>${data.title} - FinContract AI Analysis</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #1e3a5f; border-bottom: 2px solid #059669; padding-bottom: 10px; }
        h2 { color: #2563eb; margin-top: 30px; }
        .risk-score { background: #f0f9ff; padding: 15px; border-left: 4px solid #2563eb; margin: 20px 0; }
        .red-flag { background: #fef2f2; padding: 10px; margin: 10px 0; border-left: 4px solid #ef4444; }
        .suggestion { background: #f0fdf4; padding: 10px; margin: 10px 0; border-left: 4px solid #10b981; }
        .severity-high { color: #dc2626; font-weight: bold; }
        .severity-medium { color: #f59e0b; font-weight: bold; }
        .severity-low { color: #10b981; }
      </style>
    </head>
    <body>
      <h1>${data.title}</h1>
      <p><strong>Generated by FinContract AI</strong> - Trading Contract Compliance Analysis</p>
      
      <div class="risk-score">
        <h2>Overall Compliance Score: ${data.riskScore}/100</h2>
      </div>
      
      <h2>Summary</h2>
      <p>${data.summary}</p>
      
      <h2>Red Flags</h2>
      ${data.redFlags.map(flag => `
        <div class="red-flag">
          <strong class="severity-${flag.severity}">${flag.severity.toUpperCase()}</strong>: ${flag.title}
          <p>${flag.description}</p>
        </div>
      `).join('')}
      
      <h2>Suggested Improvements</h2>
      ${data.suggestions.map(sug => `
        <div class="suggestion">
          <strong>${sug.section}</strong>
          <p>${sug.suggested}</p>
          <p><em>${sug.explanation}</em></p>
        </div>
      `).join('')}
      
      <hr>
      <p style="color: #64748b; font-size: 12px;">
        This analysis was generated by FinContract AI for trading contract compliance and risk management.
        For regulatory compliance, consult with qualified legal professionals.
      </p>
    </body>
    </html>
  `;

  const blob = new Blob([htmlContent], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${data.title.replace(/[^a-z0-9]/gi, '_')}_FinContract_Analysis.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
