
-- Create a table to store legal chat histories linked to the user
CREATE TABLE public.legal_chat_histories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  title TEXT, -- Optional title for later (could be auto-generated by AI, kept nullable for future)
  chat JSONB NOT NULL
);

-- Enable RLS so only users see their own chats
ALTER TABLE public.legal_chat_histories ENABLE ROW LEVEL SECURITY;

-- Allow all users to INSERT/SELECT/UPDATE/DELETE their own chat histories
CREATE POLICY "Users can select their own legal chats"
  ON public.legal_chat_histories
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own legal chats"
  ON public.legal_chat_histories
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own legal chats"
  ON public.legal_chat_histories
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own legal chats"
  ON public.legal_chat_histories
  FOR DELETE
  USING (auth.uid() = user_id);
