// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pewmzdrzvjopdvngynhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBld216ZHJ6dmpvcGR2bmd5bmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTM1OTIsImV4cCI6MjA2MDIyOTU5Mn0.dXKhuhbEch7uEhAPUjwqHhwmMiC4XZQ45CZiZK-CWf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);